### PR TITLE
Move console icons into bramble extension images/ and update css url()s, fixes https://github.com/mozilla/thimble.mozilla.org/issues/2057

### PR DESCRIPTION
**Pull request by humphd**
I've fixed the paths and location of images being loaded for the console.  Because we only use them in the bramble extension, I've moved them there, so I don't have to have a path like "../../../../styles/...".

### CODE REVIEW

**Comment by humphd** [comment]
I'm seeing another weird CSS height thing with this:

screen shot 2017-05-11 at 11 06 27 am

I'm not sure how I've caused this, but I think it was me.  Any ideas?

**Comment by humphd** [comment]
Seems to also happen on `master` locally too.  I might as well fix it in this same PR if possible, need some advice.

**Comment by humphd** [comment]
I seem to be missing the l10n string locally, which I don't understand: why would it work on staging?  cc @gideonthomas

**Comment by humphd** [comment]
That height issue is actually missing strings, fixed in https://github.com/mozilla/thimble.mozilla.org/pull/2058.  We can just focus on the icons here.

**Comment by flukeout** [comment]
@humphd icons show up as expected in testing. R+

**Comment by raygervais** [comment]
@humphd @flukeout 

Just tested a few thoughts:
- Looks great (now that I can see the up-to-date version)! 
- Can't wait to see what others think as well!

screenshot from 2017-05-11 21-20-16

**Pull request merged**
