### PR TITLE
[WIP] Thimble + Mobile : Simulate touch events in the preview

### PR DESCRIPTION
**Pull request by Rajat-dhyani**
Brackets code for touch simulation in preview.
[fix:1660](https://github.com/mozilla/thimble.mozilla.org/issues/1660#issuecomment-287571735)

### CODE REVIEW

**Comment by Rajat-dhyani** [comment]
As we can see with  with `Inspector` feature where `MouseManagerRemote.js` is injected to iframe to listen to move event inside the iframe and `MouseManager.js` talks with rest of brackets.

So what i am facing issue is with integrating a TouchEmulatorRemote.js file to the brackets which will live inside the iframe and communicate with `TouchEmulator.js` so as to listen to touch events. Following points are to be covered to perfectly get this patch online : 

1. What to include in `TouchEmulatorRemote.js` so it communicates properly with the `TouchEmulator.js` - what i was trying to do was to imitate `MouseManagerRemote.js` and add events inside the `TouchEmulatorRemote.js` and listen to them using  `TouchEmulator.js` but could not resolve it.

2- Also if i try to listen to event as mention above `MouseManageRemote.js` gets triggered as is also listens to mouse events so how to prevent that from happening is also in todo list.

cc: @gideonthomas @flukeout @humphd

**Comment by humphd** [comment]
Most of what you have in `TouchManager.js` belongs in `TouchManagerRemote.js`.  You seem to reference `lib/TouchEmulatorRemote.js` (e.g., you `require()` it), but the file isn't in your commits.  Where is it?  The `*Remote` version of these scripts (the mouse manager, link manager, etc are all the same) is the code that lives in the iframe.  The version that lives in the editor (the non-`Remote` one) is responsible for dealing with API calls to enable/disable things--you seem to have a lot of that code in place now.

Then, it needs to communicate with the `Remote` script via messages sent on the `PostMessageTransport`, see https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/PostMessageTransport.js#L155-L182.  If the `Remote` version needs to communicate, it can send messages back too: https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/MouseManagerRemote.js#L79.

Also, it looks like you've used some existing code here for the Touch support, but there's no license or copyright info.  You can't do this in open source.  If you use someone's code, you need to retain the copyright and license info.

**Comment by Rajat-dhyani** [comment]
@humphd sir,
1- i have not added `TouchEmulatorRemote.js` because i was not sure whether i did the things correctly so i first opened a PR to get what i need there and would then add that file that being said i am stuck at this point as you can see with my PR i have traced all the path and i am sure i am very close so all i need now is the help with what part of the code should i include in `TouchEmulatorRemote.js` and what part to leave as you can see from the `TouchEmulator.js` most of the code is interlinked.
2- Yes i have used code for the touch support so i will add the license for the same thank you for informing me about that.

**Comment by Rajat-dhyani** [comment]
@humphd sir,
I have added `TouchEmulatorRemote.js` and have added Touch support to the preview panel. 
To check Touch support just left click on the preview panel and you will see a white circle listening to touch events.
But there are few issue:
<ul>
<li>Touch Starts automatically on load</li>
<li>Touch Support though starts and listen to the events like 

> shift+left click+mouse drag

 and

>  left-click

 to reflect touch support but it does not perform the required touch event.</li>
<li>The `touch-start` and `touch-stop` message are not being listened to properly. I am pretty sure that calling of function is right but internal working is need to be modified a bit</li>
</ul>

A little help in right direction is needed.

cc: @gideonthomas @flukeout @Pomax

**Comment by flukeout** [comment]
Hey @Rajat-dhyani - based on feedback from our users, I think this feature is a little too advanced to implement at this point. Thank you for the work you've started on this, we can return to it if we decide to continue with this feature. Will close for now.

**Pull request closed without merging**
