### PR TITLE
Fix mozilla/thimble.mozilla.org#1652

### PR DESCRIPTION
**Pull request by dangkhue27**
Fix mozilla/thimble.mozilla.org#1652 - Thimble hangs when deleting last HTML file and refreshing browser.

### CODE REVIEW

**Comment by humphd** [comment]
@dangkhue27 what does the editor do when it opens and there's no HTML file?  Does it give you a dialog warning you that you should have one?

**Comment by dangkhue27** [comment]
The editor gives me this message:

capture

**Comment by humphd** [comment]
Perfect!  That's what I hoped.

**Comment by gideonthomas** [comment]
My local dev environment is screwed up. I'll try this in the morning

**Comment by gideonthomas** [comment]
This works great! Thanks @dangkhue27, nice work!

**Pull request merged**
