### PR TITLE
Fix #368: fix for highlight open file on launch

### LINKED ISSUE #368: Highlight opened file on load
On load, brackets does not highlight the currently open file in the filetree. On load, this file should be in a selected state.

### PR DESCRIPTION
**Pull request by Th30**
@flukeout 
@humphd 
@gideonthomas 

Hey,

Managed to hopefully fix this problem.
screen shot 2017-02-11 at 1 59 27 pm

Let me know if you have any suggestions or addition, I'm still working on getting the white font.:)

### CODE REVIEW

**Comment by gideonthomas** [comment]
Fixes mozilla/thimble.mozilla.org#368

**Comment by humphd** [comment]
Awesome, great job.  Related work happening in #587

**Comment by flukeout** [comment]
Hi @Th30 - Unfortunately I don't think this addresses the issue. The change you've made forces the DIV that shows a file highlight to be shown with the ``display: block !important`` rule. That DIV is always there at the top location until it's shown by Brackets when a file is selected.

So, if you edit a file that is in the second location, the reload brackets, the second file will be in the Editor, but the highlight will always be shown in the first position.

**Comment by Th30** [comment]
Ah ok I'll retest and see what I need to change, I might need to check the Javascript as well, for the dynamically created files.

**Comment by flukeout** [comment]
I'll close this PR then @Th30 - happy to follow up in new PRs or other issues you want to try!

**Pull request closed without merging**
