### PR TITLE
Fix #499: Add inline editor and inline doc provider querying and events

### LINKED ISSUE #499: Provide visual indication that an inline editor or quick doc view is available
We have keyboard shortcuts for things like the inline colour picker, HTML and CSS docs, etc.  However, you have to a) know what these shortcuts are (and we don't tell you!); and b) have to know _when_ to use them (your cursor has to be placed in exactly the right spot).

I think we should provide a way for apps to signal to the user that there is some kind of helper they could use for their given cursor position.  In Thimble, for example, we might put an icon at the top that when clicked pops open the inline helper.  Or, we might choose to do this in Brackets, and put an icon to the left of the line number in the gutter.

The mechanics of making it possible are one thing, the UX another.  My _goal_ is to make it so that you can discover these features vs. just having to know.

cc @flukeout

### PR DESCRIPTION
**Pull request by humphd**
I'm going to carry on work begun by @davidhuang1550 in https://github.com/mozilla/brackets/pull/617, but do it in a slightly different way.  Thanks for getting this started and prototyping the feature.

This currently lacks any UI, but does trigger events for `editorProviderAvailable` and `docProviderAvailable`, which indicate that one could open an inline provider for the current cursor position and get something useful.

NOTE: I've done all the providers except the JS function hints, since it requires an async check that is more involved.  We could add that later if we want, but I don't think it's as critical as the ones I've done.

I've got a lot of code duplication in here, and that could be improved.  Also, I need to get @flukeout to help me figure out a good UX for exposing this info to the user, so he/she can click something and use the inline provider.

### CODE REVIEW

**Comment by flukeout** [comment]
OK, for completeness, some options include. 

* Place icon at the end of a line that the inline-editor will affect
* Place an icon in the gutter of the line that the inline-editor will affect
* Place an icon near the cursor for the property that the inline-editor will affect

Here's a mockup of these options...

image

Of these I think I like the third one, which places the icon overtop of the content that will be affected. It's close to where the cursor is so it will be easiest to click. The drawback is that will obscure whatever code is underneath it.

cc @humphd - of these options, which do you anticipate will be easiest to implement? Again, I think we could lean on the same code that powers the color preview...

image

**Comment by flukeout** [comment]
Testing now!

**Comment by flukeout** [comment]
Feedback

* Let's disable the existing Color Preview popup so it doesn't co-incide with our new ones.
  * Alternatively, we can show the Preview but make it also be clickable so that it opens the editor
  * Probably easier to just ditch it though
* When the tooltip is visible and the page is scrolled, the tooltip stays in it's original position, can we..
  * Hide it on page scroll
  * Maintain the correct position on scroll (might not be that hard, we can just check the scroll offset on a scroll event and add it to it's position
* Can we delay the popup a little bit, wait 250ms before showing it?
* Make the UI a bit more compact
  * This will help with the feeling that it's obscuring parts of the code when it's visible

**Comment by flukeout** [comment]
I'll do some work on this now @humphd and submit a PR

**Comment by flukeout** [comment]
Okay @humphd - I've got a PR up here https://github.com/humphd/brackets/pull/10 with some of the changes I described.

**Comment by humphd** [comment]
@flukeout I've merged your stuff, and am updating it to fix some things locally.  This is going to sound crazy, but your icon makes me think of https://pbs.twimg.com/profile_images/692441136472784896/KowiUPSf.jpg

**Comment by humphd** [comment]
@flukeout you should re-pull this branch and give it a test.  I think this is getting pretty close to "feeling" right.  I still need to improve a few bits of code, but let's nail down the experience.  We're close.

**Comment by flukeout** [comment]
Okay, will re-test! Oh yeah that skull thing haha. So, the true history of that icon / treatment is from the Webmaker app project. We designed that icon for what we were calling "Tinker Mode", which let you go beyond a simple UI for something like color-picking, and allow you get a fancier / more robust UI (or to add code). You can see it at the bottom of this screenshot...

https://lh3.googleusercontent.com/dGgj_XV2hwrVAVd3zA4NLCH3QDEruOQL1qfOoagKqGfnHmdmY53ZtoKG-FGR8H8mITKi=h900-rw

**Comment by flukeout** [comment]
Here's an issue I found, when the value of the edited property changes, it re-triggers showing the indicator. Is there a way to address this?

tinker-indicator

**Comment by humphd** [comment]
@flukeout take this new version for a spin when you get a minute, I've cleaned up what you found, dealt with scrolling (I hide on scroll).  I think this feels like a pretty good 1.0 version of this feature.  See if you agree or want more changes.

**Comment by flukeout** [comment]
Note(s) to self: 

* Add ``box-shadow: none`` to the arrow below the indicator to get rid of the black line seen here...
  * image

**Comment by flukeout** [comment]
Hey @humphd - this is looking and feeling much better. I submitted a PR against this branch with a minor cosmetic update.

One more thing I noticed is that after refreshing the editor, the first time you click on a line of code the indicator doesn't show up, but does so on subsequent clicks. You can see this in the GIF below. I started recording after refreshing the editor...

indicator-2nd-click

**Comment by humphd** [comment]
OK, I finally figured out the first-click bug.  @flukeout can you test again please?

**Comment by flukeout** [comment]
Sure thing @humphd testing now.

**Comment by flukeout** [comment]
Okay, this is good to go in my books, as we discussed.

**Pull request merged**
