### PR TITLE
fix for bug #454, adds _isHTML condition at HTMLServer.js:151

### PR DESCRIPTION
**Pull request by NYCJacob**
This change adds a conditional wrapper at line 151 - 170 before server(content)

### CODE REVIEW

**Comment by gideonthomas** [comment]
Hi @NYCJacob, would you be able to rebase your patch onto the latest commit on the master branch?

**Comment by NYCJacob** [comment]
will do

**Comment by NYCJacob** [comment]
ok I synced my fork with your master and did another push.  Is that good?

**Comment by gideonthomas** [comment]
@NYCJacob you would need to close this pull request and open a new one. In the new one, make sure the base fork's branch is master and not bramble.

**Pull request closed without merging**
