### PR TITLE
Fix #723, Always run unlocalize script, always build iframe API

### LINKED ISSUE #723: poststart script not running
We expected the `poststart` script to cleanup the localization changes made in the file tree when you terminate the `npm start` script. Turns out this is not the case and it never runs.

I think we have two options:
1. Listen for SIGINT and run the cleanup code via a node script
2. Use pm2 to manage the process and let it run the cleanup code

### PR DESCRIPTION
**Pull request by humphd**
Fixes #723 
@gideonthomas I'm sick of the `unlocalize` step not running when the dev server stops.  Despite what `npm` *should* do, the `post` script for `start` doesn't run in all versions of `npm`.  This fixes it so we always do it.

### CODE REVIEW

**Comment by humphd** [comment]
It works for me.  The web server exits properly on `CTRL+C`, and my unlocalize stuff runs.

**Comment by gideonthomas** [comment]
Hmm weird, it def does not work for me. Does it depend on the terminal? I'm using zsh. Also, what OS version are you using?

**Comment by humphd** [comment]
I feel like I filed another bug somewhere about helping devs not get confused when `dist/bramble.js` was missing, but I can't find it now.  This fixes that too.

**Comment by humphd** [comment]
@pomax, can you test this on Windows, please?  Run `npm start` and see if it runs the web server and localizes files.  Next, do `Ctrl+c` to kill the web server, and see if it runs the `unlocalize step`.  If you run `git status` when it's done, you shouldn't see the localized files changes in `src/nls/*`.

**Pull request merged**
