### PR TITLE
Fix: 1902 Add a way to hide the preview 

### PR DESCRIPTION
**Pull request by Rajat-dhyani**
With this PR we can now toggle the preview window in the same way as the file tree

[Fix:1902](https://github.com/mozilla/thimble.mozilla.org/issues/1902)

### CODE REVIEW

**Comment by humphd** [comment]
This is cool, @Rajat-dhyani, I've tested it locally.  A few thoughts:

* You've added a `Preview.js` module, and we should probably merge this code with `iframe-browser.js`.  Let's create a single file, `Preview.js`, which includes the code you wrote *and* what's currently in `iframe-browser.js`--I think `Preview.js` is a better name.  Make sure you also update all references to `iframe-browser.js` to `Preview.js` when you do this.
* We wrote some code a long time ago that isn't used anymore, but you could steal here to hide the second pane, see https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/lib/iframe-browser.js#L160-L161.
* It's really important with showing/hiding things in the UI that we inform any objects that rely on state, so they can fire events, etc. when things change.  Just changing the DOM elements will get us in trouble.
* An example of the above, try doing this `bramble.hidePreview(); bramble.hideSidebar();`.  You'll see that it doesn't hide the preview anymore, since the width of the first pane is now wrong.
* Don't hold references to DOM elements for the lifetime of the program (e.g., `$secondPane`, etc.).  Just get them from the DOM when you need them in your `show/hide` functions
* Don't name variables with capital letters, e.g., `width` vs. `Width`.
* Can you rebase and squash this branch so you get rid of all the merges of master above?

Let's start with these changes and then I'll review again.  This is going to be cool!  I've wanted to refactor the `iframe-browser` code for a long time.


https://github.com/mozilla/brackets/blob/master/src/view/MainViewManager.js#L1646-L1666

**Comment by Rajat-dhyani** [comment]
@humphd  would update the code accordingly it would be very cool to work on it..... Thank you for the review 👍 :)

**Comment by Rajat-dhyani** [comment]
@humphd working on this now.

**Comment by Rajat-dhyani** [comment]
Closing this branch. Please refer to this [PR](https://github.com/mozilla/brackets/pull/740) for new changes

**Pull request closed without merging**
