### PR TITLE
Experiment moving Filer provider calls to IndexedDB onto a Worker

### PR DESCRIPTION
**Pull request by humphd**
I was doing some perf audits and noticed that filesystem calls are more expensive on the main thread that I thought, especially during startup when we read/write a lot from disk.

I did an experiment to move the filesystem db operations into a worker.  I'm not sure if this is a good idea or not, I'll have to collect some data.  But it's working, if you want to try it out.

### CODE REVIEW

**Comment by modeswitch** [comment]
Can you open a PR for this on Filer?

**Comment by humphd** [comment]
@modeswitch extracting what I've done with the filesystem in general in Brackets, and making it generalized for Filer, is on my longterm list, yes.  I had to solve a bunch of the problems we always discussed, so it would be good to get that code working in Filer vs. just Brackets.  It won't happen for a bit, though.

**Comment by humphd** [comment]
@modeswitch any ideas on how I can test the performance effects of this patch?  I really want to make a decision about whether or not to take on this added complexity.  It *feels* like a big win, but I'd love some numbers.

**Comment by modeswitch** [comment]
@humphd There are the perf tests in the repo tree. If you swap out the provider that should give you a decent measure.

**Comment by humphd** [comment]
I adapted the code in filer's perf tests to allow me to keep track of the accumulated time spent in each fs call we do during startup in Thimble.  This involves a lot of operations, and is stable across runs, so it was an interesting test case.  Here's what I see:

Main Thread (numbers are total times in ms)
```
exists: 165
readFile: 3036
readdir: 6
stat: 3369
writeFile: 51
```
Worker (numbers are total times in ms)
```
exists: 56
readFile: 3360
readdir: 7
stat: 3645
writeFile: 47
```
Basically, there's no penalty for moving things on/off the worker with `postMessage`; however, running things on the worker will mean that the main thread stays more responsive (e.g., there's 3000+ms of reads above that are either going to block the main thread or the worker).

**Comment by modeswitch** [comment]
To clarify, the reads shouldn't block the main thread since they are done asynchronously, right?

This seems like an overall win. I'd like to see this done on a shared worker to allow multiple tabs/windows to run off the same Filer instance.

There are implications here for how we do blocks and block caching as well. It might make sense to keep an in-memory cache in the main thread to avoid postMessage overhead.

There's also an application here for service workers to allow apps to load themselves from Filer when there's no network. That's a bit more complicated, because service workers can disappear and restart at any time. I think Filer can handle that though.

I browsed through the patch and it doesn't look like it's that difficult to lift this into Filer directly.

**Comment by humphd** [comment]
I may be wrong, but I suspect that it still runs on the main thread, it just gets queued as a task, similar to how async xhr works.

Doing this in a shared worker is possible. I'm basically already doing this in Bramble, since we use a `MessageChannel` and `MessagePort` based `postMessage` to host the filesystem in one window, and run it in another on a second origin (i.e., Thimble hosts the Filer fs and talks to the db, and runs Bramble in an iframe, and Bramble uses `postMessage` to send the fs operations to the Thimble window).  We do this so that we can isolate the content being stored in the fs from our editor/iframe-browser, and therefore reduce scripting attacks against the app.

In order to get this to work, I had to shim `MessageChannel` for some browsers (including FF), and then further, had to deal with some browsers (Chrome) having buggy implementations of transferables and `ArrayBuffer`s.  That said, I've done it all, so moving it into a `SharedWorker` is not a huge deal.

I'd like to move more of the Filer code into the worker though, not just the provider.  I think all our manipulation of the `Buffers` would be better done on the worker as well.  So we'd make a new `interface` file that proxies to the worker.  We'll also have to deal with some browsers not allowing `SharedWorkers` (yet), see http://caniuse.com/#feat=sharedworkers.  Eventually doing something with `ServiceWorkers` would be amazing, because it would allow me to make our in-browser web server work seamlessly, without having to rewrite content to Blob URLs.

Doing this stuff in Filer is probably a good thing for the fall.  I'll likely land this patch in brackets now, and learn from it, then backport it to Filer and refine.

**Comment by humphd** [comment]
I think we should not land this, and instead bake this into Filer, and move the entire filesystem into the worker, so we can offload processing of Buffers to the worker, too.  See discussion here https://twitter.com/humphd/status/633791651362799616

**Comment by modeswitch** [comment]
https://github.com/filerjs/filer/issues/104

This wants a `proxy-interface.js`.

**Comment by modeswitch** [comment]
> Thimble hosts the Filer fs and talks to the db, and runs Bramble in an iframe, and Bramble uses postMessage to send the fs operations to the Thimble window

Does this mean you're accessed IDB in a third-party iframe? I thought this was broken in Firefox.

**Comment by humphd** [comment]
It's fixed, and doable now across the board, browser wise.

**Comment by humphd** [comment]
This was an interesting exercise, but I'm going to close because we don't need to add the overhead for our use cases.

**Pull request closed without merging**
