### PR TITLE
Remove nohost/StaticServer (dead code), always rewrite CSS files, fix remote script injection

### PR DESCRIPTION
**Pull request by humphd**
I'm slowly working up the courage to tackle #549 and add Service Worker support.  As I do, I'm re-familiarizing myself with our live dev server infrastructure.  Today, I noticed a few bugs, and this fixes things:

* We don't actually use the `nohost/StaticServer` module at all, so I've removed it.  Kind of hilarious I wrote it at all, since it's 100% dead code :)
* I've refactored the LiveDev script injection to always use what's defined in the `PostMessageTransport` vs. the hack we had in the `HTMLServer` before.  I think this might actually fix a few other scroll-position bugs that @flukeout mentioned in Thimble, specifically https://github.com/mozilla/thimble.mozilla.org/issues/1671
* I've fixed a bug in our `server.urlToPath()` method to ignore non-Blob/relative path URLs.  This was causing an exception when HTML docs included links to stylesheets on the web (i.e., we were looking for a related doc in the editor, but we don't have one because it's actually an `http://` url).
* I've fixed a bug in our initial filesystem cache logic where we were reading but not rewriting HTML and CSS files, and then serving them without also rewriting any internal links (e.g., images).  A good way to see the bug was to have a CSS that used `background-image: url(something.png);` and when you first load it, the image won't show.  You have to edit the CSS file to make it actually rewrite it, and purge the existing, incorrect cached URL from the Blob Cache.

### CODE REVIEW

**Comment by gideonthomas** [comment]
everything seems to be working fine. I do see this showing up now though:
screen shot 2017-03-29 at 4 50 19 pm
screen shot 2017-03-29 at 4 50 34 pm

**Comment by humphd** [comment]
@gideonthomas do you know what you were doing when that was caused, and/or what the project you're editing looks like (files/folders/types)?

**Comment by gideonthomas** [comment]
@humphd it's the default project and it seemed to happen when I switched files. So I'm guessing when the preview reloads?

**Comment by humphd** [comment]
@gideonthomas I can't reproduce that error.  I think we should take this patch, and fix bugs we find as a result.

**Pull request merged**
