### PR TITLE
Add catch-all Binary Viewer for non-editable types

### PR DESCRIPTION
**Pull request by humphd**
Fixes https://github.com/mozilla/thimble.mozilla.org/issues/2374.  This adds a catch-all "Binary" viewer, for file types we don't know what to do with.  The goal here is to not dump the user into a binary file (e.g., Word Doc) and have the editor lock up trying to read it as UTF8.

At the same time, we want to give them options.  They can download it, open it in a new tab, or tell Brackets to let them edit it directly:

binary-viewer

@flukeout this is only a skeleton, and I assume we'll want to clean up my code a bit, and especially fix what we show.  Maybe you can iterate on it.

Also, I noticed something when doing this that might be responsible for some of the weird bugs we've seen with viewers.  When a file is renamed, we aren't removing it from the `_viewers` object cache.  We should be, so that we don't try and open/refresh it.  I'll file a bug on that for the other viewers.

### CODE REVIEW

**Comment by flukeout** [comment]
Will be testing this today and will also start work on a styling PR

**Comment by flukeout** [comment]
@humphd I'm encountering an error, here are the steps...

* Open the editor via src/hosted 
* Clear your cache etc
* Add a file with an unrecognized extension ``bling.blam``
* The Editor switches to show the new view
* Reload the editor before doing anything else
* Editor doesn't load, stuck on spinning square loader with no error messages in console

**Comment by humphd** [comment]
Let me try to reproduce here...

**Comment by humphd** [comment]
Confirmed, I'll debug a bit and report back.

**Comment by humphd** [comment]
@flukeout I think I fixed it, try testing with my latest commit.

**Comment by Pomax** [comment]
It would be cool if this gave two "open" options: "try to open anyway" and "edit as binary data" that fires up a hex editor - a utility I **constantly** wish I had available in all my editors, because it makes it really easy to both demonstrate how files work, and do edits that would otherwise need big tools (like resizing a jgp in-file... just change 2 bytes and "magic" that you can teach others has happened, without ever using an image editor)

**Comment by flukeout** [comment]
@humph - confirmed that your latest commit fixes the issue I found.

**Comment by humphd** [comment]
@Pomax I mean...https://xem.github.io/hex/...we could?

**Comment by humphd** [comment]
Man, there are a lot of these around http://mikach.github.io/hex-editor/

**Comment by flukeout** [comment]
@humphd...

* I made a PR with some styling and localization updates against this branch 
  * https://github.com/humphd/brackets/pull/12
* Here's the Thimble PR with the required strings
  * https://github.com/mozilla/thimble.mozilla.org/pull/2428

**Comment by humphd** [comment]
Let's merge this when I get back from holiday.

**Comment by flukeout** [comment]
Ping @humphd - I think this is good to go now.

**Comment by humphd** [comment]
OK, landed.  Let's test this on staging this week, and make sure we're happy with how it all happens now.

**Pull request merged**
