### PR TITLE
Drag files out of the browser

### PR DESCRIPTION
**Pull request by humphd**
This is a WIP, but I don't want to lose track of it, so I'm submitting this PR.  I'll do it on top of my dnd-folders branch, when that goes in.  This will need a rebase when that happens.

### CODE REVIEW

**Comment by humphd** [comment]
I've rebased this on top of `master` now that #659 has landed.  It's ready for testing/review.

To test this:

* Run Chrome (this only works in Chrome, though it won't crash in other browsers)
* Drag a file from the file tree to your desktop
* The file should appear on your desktop with the proper filename

I still have a CSS issue I can't fix.  Clicking on nodes in the filetree is drawing a blue border:

blue-border

@flukeout suggested removing the `box-shadow`, but that doesn't seem to solve it totally for me.  I could use some help figuring that out.

**Comment by Pomax** [comment]
code looks pretty sane to me.

**Comment by flukeout** [comment]
I think we agreed to remove this from launch since it's a fringe, hard to discover (but awesome!!) feature.

**Comment by flukeout** [comment]
@humphd Should we land this now?

**Comment by humphd** [comment]
I rebased this, and tested again.  Works well.  I'll land after it passes travis.

**Pull request merged**
