### PR TITLE
Add extra padding before the start of each line in the editor #1875

### PR DESCRIPTION
**Pull request by sanariaz154**
fixes [#1875](https://github.com/mozilla/thimble.mozilla.org/issues/1875)
removed unnecessary files and changes.

### CODE REVIEW

**Comment by Pomax** [comment]
Hi @sanariaz154 thanks for the PR! As a helpful github.com administration issue, can you add the line "fixes #1875" to your PR comment? That way github will set up a crosslink between the PR and the associated issue, and landing the PR will then automatically close the issue with it.

**Comment by flukeout** [comment]
Hi @sanariaz154 - thank you for the PR. I have some feedback

* Please put your style changes into ``bramble_overrides.css``
  * ``brackets_codemirror_override.less`` was created by the Brackets team and I worry that if they update it in a new version, we may lose our changes.
  * We have full control over ``bramble_overrides.css`` is our own file, so I think it's the better choice
* Your change also introduces extra spacing before the line numbers in the editor, which we don't want, here's a side by side...
  * Let me know if you can see the different I'm talking about


In the issue related to this you mentioned that changes to ``bramble_overrides.css`` aren't working. I was able to make changes in that file to get a similar effect to your changes. Are any CSS changes in that file working for you?

Thanks!

**Comment by humphd** [comment]
@sanariaz154 in case it's not obvious, you can run Brackets with `npm start` and then navigate to `http:localhost:8000/src/hosted.html` and you'll get just the editor without Thimble.  When I'm working on fixes just in Brackets, I tend to debug that way, which makes it a bit easier.

@flukeout you mention a "side by side" but didn't attach it, fyi.

**Comment by flukeout** [comment]
Updated with a screengrab.

**Comment by sanariaz154** [comment]
@flukeout    I understand  what you are saying I didn't notice the space before linenumbers before. 

 - I was getting this error  when I did changes in `bramble-overrides.css`  
   ` FileError:"http://localhost:8000/src/styles/bootstrap/utilities.less"  was'nt found(0)`
     but know the error is not showing and issue is resolved .

- @humphd i was also running Brackets this way .
     Thanks

**Comment by flukeout** [comment]
Testing now, thank you!

**Comment by flukeout** [comment]
Thank you for updating the PR, here is some feedback

* Please remove any changes to ``brackets_codemirror_override.less`` it should not be a part of this PR
* Please fix up your whitespace and indentation in your code, it should match the rest of the file and be consistent, your changes currently look like this...

image

Please indent and space the code consistently.

Lastly, in your PR, the DIV that acts as a click target for the code-folding arrows doesnt line up with the arrows anymore, take a look here, I'm highlighting it in the DOM

image

It has stayed a bit to the left, so clicking on some parts of the arrows doesn't work. To fix this, here's what you can add to your PR, this will move the click area to the right by 8 pixels and line it up with the arrows...

```
.CodeMirror-foldgutter {
  transform: translateX(8px);
}

.CodeMirror-foldgutter:after {
  display: none;
}
```

Thank you!

**Comment by flukeout** [comment]
OK, testing now!

**Comment by flukeout** [comment]
Ok, great! Works well as far as I can tell so we'll merge it! @humphd has had trouble with this kind of change in the past, so let's all keep an eye on this to see if causes any unexpected problems.

Thank you again @sanariaz154!

**Comment by humphd** [comment]
Thanks a lot, @sanariaz154.  Looking forward to having you work on other bugs with us.  Appreciate the contribution.

**Comment by sanariaz154** [comment]
Thank you @flukeout  @humphd . you've been very supportive .I would like to work more ,I've searched from thimble.mozilla.org's issues labeled as good-first-bug but most of them are assigned. Can you please suggest me some other good first issues which are not yet assigned to anyone?

**Comment by humphd** [comment]
#889 is one you could do.  It's assigned, but I don't think he's working on it.  If you are interested, I'll ask him to let you do it.  https://github.com/mozilla/thimble.mozilla.org/issues/1251 is another one you might be good at, since it also deals with CSS in Brackets, but would be a bit more challenging.  https://github.com/mozilla/thimble.mozilla.org/issues/1588 is another I'd like to see, where you can right-click and "Beautify" your code to make it clean and tidy.

**Pull request merged**
