### PR TITLE
Fix mozilla/thimble.mozilla.org#2252: Change position of Download action in the right-click menu

### PR DESCRIPTION
**Pull request by serendicoder**
Fixes [#2252](https://github.com/mozilla/thimble.mozilla.org/issues/2252)

### CODE REVIEW

**Comment by flukeout** [comment]
Thanks very much for submitting @serendicoder - I'll test it out tomorrow.

Could you please add the following text to the PR description...

* ``Fixes #XXXX`` - where XXXX is the number of the issue this addresses?

This way, once this is merged, that issue will be automatically closed. Thanks!

**Comment by gideonthomas** [comment]
@flukeout it's in the commit itself so it should close automatically as well. @serendicoder, however, it would be good to mention the issue description (what is this pr fixing) in the pr description as well so that reviewers know immediately what this pr is meant to do.

**Comment by serendicoder** [comment]
Thanks @flukeout and @gideonthomas. I have added the link to the Thimble issue in description.

**Comment by humphd** [comment]
Nice job, @serendicoder, thanks for contributing to Thimble and Brackets.

**Pull request merged**
