### PR TITLE
Adding a toggle for the context menu on each file & folder item

### PR DESCRIPTION
**Pull request by flukeout**
Adding this so that a right-click, which is difficult and not discoverable (and won't work on mobile) isn't the only way to open the file tree context menu. I'm adding a little toggle element to each item in the file tree.

image

**Testing**
Here's how this should all work...

* You can still right click anywhere on files and in the sidebar and bring up the context menu as always
* In addition, when you hover a file, or when it's opened, you'll see a dropdown arrow you can click to open a context menu for that file or folder. When opened this way...
  * The folder menu contains all of the same actions as usual
  * The file menu only has the ``Rename`` and ``Delete`` options
* There is only a light theme for the context menu

cc @humphd @Pomax @gideonthomas - would appreciate if any of you could do some functional testing to make sure the menus work as you would expect.

**In addition**
* Removed double-click to edit file name
  * https://github.com/mozilla/thimble.mozilla.org/issues/2334

Fixes https://github.com/mozilla/thimble.mozilla.org/issues/1135

### CODE REVIEW

**Comment by flukeout** [comment]
Updating styling, looking to ditch 'dark theme' for the menu.

image

**Comment by flukeout** [comment]
One thing I noticed so far is some strange styling on the context menu when it's opened by right clicking the editor content, like this...

image

**Comment by humphd** [comment]
This is so cool!  I really think this will help people discover those options a lot more easily.  
A few observations about how it feels to use it:

right-click

One thing is that it's a bit of a mystery where you're supposed to click, since we use the selection cursor for the file item in the tree, but also now this drop-down.  And there's no border around the arrow to tip you off as to where you should click--you have to be right on it.

Could we do a hover treatment to expose a background border around the click area?  In the light theme I see one, but in the dark theme it's pretty much impossible to distinguish.  I realize this won't work with touch events.  Also, could we make the clickable region larger?

I'll review the code now, but the feature as a whole works really well.  Tested in Chrome, Firefox, and Safari on Mac, and Edge on Windows...all work identically.  Great job!

**Comment by flukeout** [comment]
Improved the hover effect on the dark theme. Mergin'!

**Pull request merged**
