### PR TITLE
Fixed: 1135 Added alternative to right-click in file pane

### PR DESCRIPTION
**Pull request by Rajat-dhyani**
I have added a drop-down icon, next to currently selected file and used the existing right-click menu so as to add an alternative to right-click in file pane. 😄 
[Fix : 1135](https://github.com/mozilla/thimble.mozilla.org/issues/1135)

### CODE REVIEW

**Comment by flukeout** [comment]
Just testing this out and it's looking great! Question for you though @Rajat-dhyani, is it possible to change what shows up in the menu if it's opened from a file, versus by right clicking somewhere else?

For example, when I click the dropdown icon I see the following...

image

But, in this context "New File" and "New Folder" don't really make any sense. Could we add a special class or something to the menu when we open it like this so we can hide some items?

**Comment by flukeout** [comment]
Ok, I think I found a way to do it. I'll continue work within your branch for now as I figure this out.

image

**Comment by flukeout** [comment]
What I've done above works pretty well, I just need to figure out how to give it the "context-node" class

**Comment by Rajat-dhyani** [comment]
greetings sir @flukeout ,
I have removed new file and new folder option. i have also added "Move To... " command but its not working, i am getting no errors. This is what is happening : 
 when we call  [this method ](https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble-move-file/MoveToDialog.js#L189)  it is designed to getContext() from ProjectManager class we need to do the same for my dropdown element. but for this i will have to write a whole new API just like ProjectManager.  Can you suggest some work-around on this ?

Also why you want to add "context-node" class to this element?

And there is no such default-built in "Duplicate File" action in brackets.  [Here is the list](https://github.com/mozilla/brackets/blob/master/src/command/Commands.js#L34-L61) of all the commands that we can possibly have for file related action. Though this is a very nice feature to have we can address this in another issue.

**Comment by flukeout** [comment]
The ``context-node`` class would be nice just so we can add styling to the file item when the menu is open, but it's not super important that we have it.

I'll see if I can make any progress on the ``getContext()`` method.

**Comment by Rajat-dhyani** [comment]
greetings sir @flukeout ,
I think we can add more than one class in dom element itself by simply adding the class name after a space. Should i add `context-node` class to it along with `dropdown-arrow`?

I am also working on getContext() thing and will update you soon. Do let me know if you find anything here.

**Comment by flukeout** [comment]
Okay, just ping me if you make any progress here - thank you! I'll do the same. The ``context-node`` class gets added to the entire ``li`` element that contains the file item, not just the arrow element. That' show it works when you right-click something currently.

**Comment by flukeout** [comment]
Short update on this. I poked around a bit and found a way to add a toggle to each file element and use it to open a menu for that file in the correct place. Rough version looks like this...

image

I'll probably create a new PR with this approach tomorrow.

**Comment by flukeout** [comment]
@Rajat-dhyani Thank you for starting this issue! I've addressed in in https://github.com/mozilla/brackets/pull/838 so will be closing this PR. Cheers!

**Pull request closed without merging**
