### PR TITLE
[WIP] Added file system level collaboration

### PR DESCRIPTION
**Pull request by hkirat**
This PR implements the next step for collaboration, keeping file systems in sync.

### CODE REVIEW

**Comment by gideonthomas** [comment]
@hkirat can you rebase this branch as well?

**Comment by hkirat** [comment]
I think this is up to date with collaboration @gideonthomas 
Could you check and let me know?

**Comment by hkirat** [comment]
I think the reason the previous commits are showing up is because the previous PR was squashed.

**Comment by hkirat** [comment]
Implemented comments mentioned here: 
https://github.com/mozilla/thimble.mozilla.org/issues/2351

**Comment by gideonthomas** [comment]
@hkirat, this PR is a bit of a mess at the moment. Can you clean this up? My suggestion is to close this PR and open new ones. Keep in mind that each PR (and thus each branch) should only address 1 issue ideally (this PR seems to be fixing multiple issues making it really hard to read). Don't hesitate to open multiple PRs. Whenever you see that you're out of date with the branch you're merging into, always rebase, don't merge. If you need to (due to squashing of commits, or something else), use `git rebase --onto` (https://content.pivotal.io/blog/git-rebase-onto is a good description of it), so that the PR's commits always stay at the top. Without that it becomes really hard to review.

**Comment by hkirat** [comment]
Closing for now.
Will work on file system collaboration after a little restructuring in the current collaboration branch

**Pull request closed without merging**
