### PR TITLE
Removed code folding feature

### PR DESCRIPTION
**Pull request by flukeout**
And also removed the gutter border, so code should appear like this...

image

Moved the ``CodeFolding`` extension to the optional list.

This also resolves the issue where the QuickEdit box is shifted too far to the right...
https://github.com/mozilla/thimble.mozilla.org/issues/1906

### CODE REVIEW

**Comment by humphd** [comment]
Testing this, I notice two issues with inline editors.

The first is with the dark theme, and might be due to that other bug where we don't honour the dark theme in editors (see the titlebar): 

screen shot 2017-03-29 at 1 21 50 pm

The second is in the light theme, and there is an odd block of white on the left:

screen shot 2017-03-29 at 1 22 22 pm

I'm not sure if you want to deal with either of those here, or file new bugs on them?

**Comment by flukeout** [comment]
Okay, feedback addressed...

themes

Themes work correctly and no more weird spacing / color gaps.

**Comment by humphd** [comment]
This is great, r+ with a passing Travis build.  Please squash and merge it once the build is green.

**Comment by humphd** [comment]
I've also removed the Code Folding section from the wiki pages about how to use Thimble.

**Comment by flukeout** [comment]
Feedback addressed & merged @humphd - also snuck in some Resizing UI changes.

**Pull request merged**
