### PR TITLE
Add Font View based on https://github.com/TomMalbran/brackets-fonts-viewer

### PR DESCRIPTION
**Pull request by humphd**
I modified this font viewer to work in Bramble, and changed it a bit:

screen shot 2017-06-29 at 2 53 40 pm

I'm sure @flukeout can improve my UI.  The [way Google does their font display](https://fonts.google.com/specimen/Spectral) is maybe something to look at for inspiration.  @Pomax, you're the font expert, please weigh in as well.

It would also be nice to allow the user to select/view different sizes (buttons or a dropdown?), and have some boilerplate code you can copy/paste to use this font in your CSS.

### CODE REVIEW

**Comment by humphd** [comment]
Fixes https://github.com/mozilla/thimble.mozilla.org/issues/2339

**Comment by Pomax** [comment]
Given that individual font files only contain a single typeface, it's very weird to see this previewer pretend that there's an "italic" and "bold" version of this font. For individual font files, there's only the one style and that's it.

**Comment by humphd** [comment]
I was just playing around with `font-style` and `font-weight`, happy to remove it.  It was more "here is what this will look like if you do various things with it".

**Comment by flukeout** [comment]
Testing this out now

**Comment by flukeout** [comment]
@humphd I'm able to run this branch and load fonts in the viewer, but things are just being displayed in Times New Roman, no matter the font...

image

I'm dragging fonts into the sidebar to upload them. Are there any other steps I should try?

**Comment by humphd** [comment]
Did you manage to get this working?  Was it SW cache related, or is this a real bug?

**Comment by flukeout** [comment]
Will check again shortly, but seeing as the PDF stuff is working fine now I bet this will too.

**Comment by flukeout** [comment]
Oh crap, I screwed up the merge fix.

**Comment by flukeout** [comment]
Made a PR against your branch @humphd with some updates. Did I do localization right there?

**Pull request merged**
