### PR TITLE
Quick Edit symbol fix

### PR DESCRIPTION
**Pull request by Shank09**
In the keyboard.json file there was additional key bind for Quick Edit `"key": "Alt-E".`

A function in brackets/dist/main.js replaces `Ctrl`, `Alt` to Mac equivalent. Then a function `c(e)` displays the symbol of the keys. Since the keyboard.json had `Alt` it caused it to display `⌥`

By removing `"key": "Alt-E"` it was able to interpret the correct symbol.

This pull request will resolve issue [#1528](https://github.com/mozilla/thimble.mozilla.org/issues/1528) in the thimble.mozilla.org repo

### CODE REVIEW

**Comment by gideonthomas** [comment]
My gut instinct is that this isn't the right fix (the key binding is in an array so it should show preference to the first element in the array as opposed to the second). I'll investigate this a bit more and add some comments here asap.

**Comment by Shank09** [comment]
More info:
It seems that its taking into account the second item in the array. 

When I had `Alt+E` the last element I shows the alt symbol ⌥. 
screen shot 2017-02-08 at 8 34 47 pm

Here I switched them, Alt first then Ctrl.
screen shot 2017-02-08 at 8 33 03 pm

On mac when i try `Alt E` it doesn't open up the Quick edit. Instead it inserts ´. However in Windows it opens Quick Edit.
screen shot 2017-02-08 at 8 44 15 pm

**Comment by gideonthomas** [comment]
@Shank09 yes you are absolutely correct. I dug into it and the code that does it is [here](https://github.com/mozilla/brackets/blob/master/src/command/Menus.js#L232-L233). It always chooses the last key binding in the array, so the order in the array is not "highest-priority first", but is actually "highest-priority last". 

I think the fix here would be not to delete the `Alt+E` key binding from `keyboard.json`, but to swap the order the two key bindings are in.

**Comment by Shank09** [comment]
@gideonthomas I don't have brackets installed on my Windows VM. But don't you think that changing the order of the key binds will cause Ctrl+E to be displayed for windows users.

Currently on the live version of thimble on windows I can see the Alt E is being displayed. 

screen shot 2017-02-08 at 10 51 19 pm

**Comment by gideonthomas** [comment]
@Shank09, on Windows, does `Ctrl+E` not open Quick Edit?

**Comment by Shank09** [comment]
@gideonthomas 
Both `Alt+E` and `Ctrl+E` opens the quick edit on windows only. 

From my personal experience, I feel like `Cmd+E`, and `Ctrl+E` are too close to `Cmd+W`/`Ctrl+W` and I tend to close the tab by accident, and have to goto history and pull back the page.
However `Alt+E`, is safer because the user won't accidentally close the application.  
I can see that this is similar to [#1526](https://github.com/mozilla/thimble.mozilla.org/issues/1526)

**Comment by gideonthomas** [comment]
I don't know if I agree with that (I don't believe we've received that feedback from users but at the same time not a lot of users know about Quick Edit). One thing I want to make sure is that it is consistent on Mac and Windows. If it's `Ctrl+E` on Windows, it should be `Cmd+E` on Mac and if it is `Alt+E` on windows, it should also be `Alt+E` on Mac.

If we decide to stick with `Cmd+E`/`Ctrl+E`, your change would simply need to swap the order of the bindings in the array and it should work on both platforms correctly. (I think this might be the easier solution)

If we decide to go with `Alt+E`/`Alt+E`, then, you can try removing the `Ctrl+E` binding in that file and see what happens. If for some reason `Alt+E` does not trigger Quick Edit,  we would need to spend some time investigating that.

@humphd what do you think? `Cmd`/`Ctrl` or `Alt`?

**Comment by humphd** [comment]
For context, we changed this in #421.  cc @Pomax.

**Comment by humphd** [comment]
@Shank09 sorry for the back and forth on this, let's go with @gideonthomas' idea to support both, and just swap the order, such that the alt-e one comes first, ctrl-e second.  Then I think we'll do what we want in terms of supporting the existing binding, and being more expected on mac.

**Comment by Shank09** [comment]
@humphd No problem, I made the swap.

**Comment by Pomax** [comment]
As a windows user, alt-e is a universal program shortcut for the "edit" menu, and should not be stolen by a webpage.

**Comment by gideonthomas** [comment]
Nice work @Shank09! Thanks for being patient while we figured out a workable solution!

**Pull request merged**
