### PR TITLE
thimble Issue1745 - Add backend side to support allow edit svg as xml

### PR DESCRIPTION
**Pull request by peiying16**
To make this works, you need to add UI at thimble side
https://github.com/mozilla/thimble.mozilla.org/pull/1891

### CODE REVIEW

**Comment by humphd** [comment]
Let's try to add some code to fix your "can't switch at runtime without a refresh" bug.  Here are some thoughts:

When an `ImageView` is created, it happens here: https://github.com/mozilla/brackets/blob/master/src/editor/ImageViewer.js#L386.  We can see that the first thing this does is to try and locate an existing view for this filepath (basically, is there one already open, if so show it, otherwise create a new one): https://github.com/mozilla/brackets/blob/master/src/editor/ImageViewer.js#L331-L339.  What if you just changed this to handle SVG files differently.  If you have an SVG filepath and there is an existing pane, just call `destroy()` and then do the code to make a new one here https://github.com/mozilla/brackets/blob/master/src/editor/ImageViewer.js#L336-L337.

**Comment by peiying16** [comment]
Thanks for helping me, I will try calling destroy() and create a new one later, but I don't think it will fix it. Because a new image file should not has an existing pane, but I will still try this way.

Here is my thought:
If it is a new SVG file. The path of this file is not in the array of _openDocuments.
https://github.com/mozilla/brackets/blob/master/src/document/DocumentManager.js#L125
As a result, it returns null.

If I refresh the page, the path of this file is in the array, and it returns _openDocuments[id]

If the new file is an HTML file, the path of this file is in the array, and it returns _openDocuments[id]

I think there should be something different between when it adds an image file and an HTML file. Anyone knows what the _openDocuments is.

**Comment by humphd** [comment]
@peiying16 so is this fixed and ready for review, or are you still having trouble?  If you need help, let's try to talk this week after class so we can get this all finished.  If it's fixed and ready, I'll review.

**Comment by peiying16** [comment]
@humphd I have worked on this issue for 1 month, I try a lot of modification but I still cannot fix this bug. So I give up. If anyone is interested in this issue, they may be interested in this code.

**Comment by ryanwarsaw** [comment]
Don't give up, you're so close! 🎉  I'm sure @humphd will be able to help you, or if you haven't already join the Thimble channel in Mattermost (https://chat.mozillafoundation.org/)! Ton of awesome folks that are willing to help you and answer questions \o/

**Comment by peiying16** [comment]
Thanks. ryanwarsaw.  I think this should be closed.

**Pull request closed without merging**
