### PR TITLE
update incorrect overshoot calculation

### PR DESCRIPTION
**Pull request by Pomax**
this updates the code such that it aligns with the code comment explaining what's supposed to happen: https://github.com/mozilla/brackets/blob/0b1df34a85dfb4874a0cfc4b3d7299916d84ebe6/src/filesystem/impls/filer/lib/ImageResizer.js#L66-L68

fixes https://github.com/mozilla/brackets/issues/863

### CODE REVIEW

**Comment by humphd** [comment]
@flukeout see if you're happy with the effect of this change on real images.

**Comment by flukeout** [comment]
@humphd @Pomax what am I looking for when testing this functionally? Our current approach tries to pick a size that is roughly around, but under 250kb. Does this change that?

**Comment by flukeout** [comment]
Okay - testing images large and small and will report back if I see any weird stuff.

**Comment by flukeout** [comment]
Seems to work as before! Good to merge.

**Pull request merged**
