### PR TITLE
<Thimble> Fix #2232: Use a darker color for right-clicked selected file indicator

### PR DESCRIPTION
**Pull request by auracle**
mozilla/thimble.mozilla.org#2232

@flukeout @humphd

### CODE REVIEW

**Comment by flukeout** [comment]
Hey @auracle - thanks, will test now!

**Comment by flukeout** [comment]
Hey awesome, tested and works as expected!...

image

**Comment by auracle** [comment]
Excellent! Thanks

**Comment by humphd** [comment]
Great job, @auracle!  Thanks for all your recent contributions to Thimble.

**Pull request merged**
